// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmqbkdsiarozjmowasjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtcWJrZHNpYXJvemptb3dhc2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NDMwOTYsImV4cCI6MjA3MzMxOTA5Nn0.s6VgvD5_XC3SyNXuKRRFUnWaKsEXTRyN-b6l33rNFXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});